### ISSUE TITLE
Howto migrate new Polygon token

### ISSUE THREAD

**Issue by zz64** [AmbireTech/adex-protocol#71]
Hi,

I have a small fund on the old Token on Polygon, how can I recover it in the new one ?

![funds](http://152.228.173.205/files/ADEX_1.jpg)

![1inch](http://152.228.173.205/files/ADEX_2.png)

![Wallet older Polygon adress](http://152.228.173.205/files/ADEX_3.png)

Thanks.

**Comment by Ivshti** [comment]
We don't have a new and old ADX token on Polygon, not sure how to answer this one
